//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guest()
        {
            this.listfunctions = new HashSet<listfunction>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string tenuser { get; set; }
        public string gmail { get; set; }
        public string diachi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listfunction> listfunctions { get; set; }
    }
}
