//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAjax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsTestEntities : DbContext
    {
        public NewsTestEntities()
            : base("name=NewsTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<guest> guests { get; set; }
        public virtual DbSet<listfunction> listfunctions { get; set; }
        public virtual DbSet<tacgia> tacgias { get; set; }
        public virtual DbSet<tintuc> tintucs { get; set; }
    }
}
